/*
	Challenge: 4
	Source: Project Euler

	Instruction:
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var evenFibonacci = function() {
	var fiboArr = [1,2];
	var fiboSum = 0;
	while ( fiboArr[fiboArr.length-1] < 4000000 ) {
		fiboArr.push( fiboArr[fiboArr.length-1] + fiboArr[fiboArr.length-2] )
	}
	fiboArr.pop();
	for ( var i = 0; i < fiboArr.length; i++ ) {
	    fiboSum += fiboArr[i];
	}
	return fiboSum;
}

evenFibonacci();